name: CI - Self-Healing Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: write
  contents: read
  issues: write
  checks: write

env:
  RUNNER_TEMP: /tmp

jobs:
  test:
    name: Run simulated app (build/test)
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      test_result: ${{ steps.set_result.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run simulate_app
        id: run_test
        run: |
          set -e
          echo "Running simulate_app.py..."
          python simulate_app.py 2>&1 | tee run_output.log || echo "APP_FAILED" > failed.flag

      - name: Determine test result
        id: set_result
        run: |
          if [ -f failed.flag ]; then
            echo "result=failure" >> $GITHUB_OUTPUT
          else
            echo "result=success" >> $GITHUB_OUTPUT
          fi

      - name: Upload raw run output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: raw-run-output
          path: run_output.log

  self_heal:
    name: Self-healing diagnostics & remediation
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.outputs.test_result == 'failure'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps for diagnoser
        run: |
          pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run diagnostics and remediation
        id: diag
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
          set -euo pipefail
          python scripts/diagnose_and_fix.py || true
          # The script writes "HEALED" or "UNHEALED" into ./heal_status.txt

      - name: Upload diagnostics artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selfheal-artifacts
          path: |
            diagnostics.log
            heal_status.txt
            run_output.log
            extra_logs/

      - name: Take action rerun or open issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
          set -euo pipefail
          STATUS=$(cat heal_status.txt || echo UNHEALED)
          echo "Heal status => $STATUS"

          if [ "$STATUS" = "HEALED" ] && [ "${RUN_ATTEMPT:-1}" -lt 3 ]; then
            echo "Re-running workflow (attempt ${RUN_ATTEMPT})..."
            API="https://api.github.com/repos/${REPO}/actions/runs/${RUN_ID}/rerun"
            curl -s -X POST -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                 -H "Accept: application/vnd.github+json" $API || true
          elif [ "$STATUS" = "HEALED" ]; then
            echo "Max attempts reached, stopping reruns."
          else
            echo "Creating issue for persistent failure..."
            TITLE="CI Self-Healer: Failure persists on run ${{ github.run_number }}"
            BODY="Automated self-healing failed.\n\nRepository: ${REPO}\nRun: ${{ github.server_url }}/${REPO}/actions/runs/${RUN_ID}\n\nLogs attached as artifacts."
            curl -s -X POST -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                 -H "Accept: application/vnd.github+json" \
                 https://api.github.com/repos/${REPO}/issues \
                 -d "$(jq -n --arg t "$TITLE" --arg b "$BODY" '{title:$t, body:$b, labels:["ci-failure","self-heal"] }')" || true
